# Generated by Django 4.2.13 on 2024-10-18 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDocuments',
        ),
    ]
