# Generated by Django 4.2.13 on 2024-10-18 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_delete_userdocuments'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport_front', models.ImageField(upload_to='documents/')),
                ('passport_back', models.ImageField(upload_to='documents/')),
                ('diploma', models.ImageField(upload_to='documents/')),
                ('certificate', models.ImageField(upload_to='documents/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
