# Generated by Django 4.2.13 on 2024-10-20 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdocuments',
            options={'verbose_name': 'Документ студента', 'verbose_name_plural': 'Документы студента'},
        ),
    ]
