# Generated by Django 4.2.13 on 2024-10-20 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_userdocuments_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdocuments',
            name='status',
            field=models.CharField(choices=[('consideration', 'На рассмотрении'), ('approved', 'Одобрено'), ('denied', 'Отказано')], default='consideration', max_length=100),
        ),
    ]
