# Generated by Django 4.2.13 on 2024-07-05 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name_plural': 'Quizes'},
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='correct',
            new_name='is_correct',
        ),
    ]
