# Generated by Django 4.2.13 on 2024-07-10 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_alter_quiz_options_rename_correct_answer_is_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='practice',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quiz',
            name='required_score_to_pass',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
