# Generated by Django 4.2.13 on 2024-10-14 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='number_of_questions',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='practice',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='time',
        ),
        migrations.AddField(
            model_name='question',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='status',
            field=models.CharField(choices=[('incompleted', 'Незаконченное'), ('completed', 'Законченное')], default='incompleted', max_length=30),
        ),
    ]
