# Generated by Django 4.2.13 on 2024-10-14 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_remove_quiz_number_of_questions_remove_quiz_practice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
