# Generated by Django 4.2.13 on 2024-10-20 04:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0010_alter_result_quiz'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_list', models.JSONField()),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exam.result')),
            ],
        ),
    ]
