# Generated by Django 4.2.13 on 2024-10-20 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0011_resultanswers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resultanswers',
            old_name='answer_list',
            new_name='answer_dict',
        ),
    ]
