# Generated by Django 4.2.13 on 2024-07-12 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='duration2',
            new_name='duration',
        ),
    ]
