# Generated by Django 4.2.13 on 2024-07-12 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_rename_duration2_course_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='status',
        ),
    ]
