# Generated by Django 4.2.13 on 2024-07-14 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_lecture_duration_alter_lecture_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='language',
            field=models.CharField(choices=[('Русский', 'Русский'), ('en', 'Английский'), ('kg', 'Кыргызский'), ('uz', 'Узбекский'), ('kz', 'Казахский'), ('tj', 'Таджикский'), ('cn', 'Китайский')], max_length=15),
        ),
    ]
