# Generated by Django 4.2.13 on 2024-07-16 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_course_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='text',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='course',
            name='language',
            field=models.CharField(choices=[('Русский', 'Русский'), ('Английский', 'Английский'), ('Кыргызский', 'Кыргызский'), ('Узбекский', 'Узбекский'), ('Казахский', 'Казахский'), ('Таджикский', 'Таджикский'), ('Китайский', 'Китайский')], max_length=15),
        ),
    ]
