# Generated by Django 4.2.13 on 2024-09-06 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_course_text_alter_course_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='credit_type',
            field=models.CharField(choices=[('cme', 'CME'), ('ce', 'CE'), ('other', 'Другое')], default=('other', 'Другое'), max_length=50, verbose_name='Тип кредитования'),
        ),
        migrations.AddField(
            model_name='course',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Начальный'), ('intermediate', 'Средний'), ('advanced', 'Продвинутый')], default=('beginner', 'Начальный'), max_length=50, verbose_name='Сложность'),
        ),
        migrations.AddField(
            model_name='course',
            name='specialization',
            field=models.CharField(choices=[('cardiology', 'Кардиология'), ('neurology', 'Неврология'), ('orthopedics', 'Ортопедия')], default=' ', max_length=50, verbose_name='Специализация'),
        ),
    ]
