# Generated by Django 4.2.13 on 2024-09-07 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_course_credit_type_course_difficulty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
