# Generated by Django 4.2.13 on 2024-09-11 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_lecture_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='status',
            field=models.CharField(choices=[('incompleted', 'Незаконченное'), ('completed', 'Законченное')], default='incompleted'),
        ),
    ]
