# Generated by Django 4.2.13 on 2024-09-11 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_lecture_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='type',
            field=models.CharField(choices=[('file', 'PDF-файл'), ('video', 'Видео')], max_length=10),
        ),
    ]
