# Generated by Django 4.2.13 on 2024-10-03 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_alter_lecture_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='completion_percent',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
