# Generated by Django 4.2.13 on 2024-10-03 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_course_completion_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.CharField(choices=[('36', '36'), ('72', '72')], max_length=10),
        ),
    ]
