# Generated by Django 4.2.13 on 2024-10-03 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_alter_course_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='description',
            new_name='short_description',
        ),
    ]
