# Generated by Django 4.2.13 on 2024-10-08 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0013_rename_description_course_short_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecture',
            name='status',
        ),
        migrations.CreateModel(
            name='UserLecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('incompleted', 'Незаконченное'), ('completed', 'Законченное')], default='incompleted')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.lecture')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
