# Generated by Django 4.2.13 on 2024-10-08 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_remove_lecture_status_userlecture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserLecture',
        ),
    ]
