# Generated by Django 4.2.13 on 2024-10-09 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_userlecture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlecture',
            name='status',
            field=models.CharField(choices=[('incompleted', 'Незаконченное'), ('completed', 'Законченное')], default='incompleted', max_length=30),
        ),
    ]
