# Generated by Django 4.2.13 on 2024-07-10 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercourse',
            name='finish_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='usercourse',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
