# Generated by Django 4.2.13 on 2024-07-10 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='finish_date',
        ),
        migrations.RemoveField(
            model_name='course',
            name='start_date',
        ),
        migrations.AddField(
            model_name='usercourse',
            name='finish_date',
            field=models.DateTimeField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usercourse',
            name='start_date',
            field=models.DateTimeField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.CharField(choices=[('36', '36ч'), ('72', '72ч')]),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='language',
            field=models.CharField(choices=[('ru', 'Русский'), ('en', 'Английский'), ('kg', 'Кыргызский'), ('uz', 'Узбекский'), ('kz', 'Казахский'), ('tj', 'Таджикский'), ('cn', 'Китайский')]),
        ),
    ]
