# Generated by Django 4.2.13 on 2024-07-10 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_course_finish_date_remove_course_start_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercourse',
            name='finish_date',
        ),
        migrations.RemoveField(
            model_name='usercourse',
            name='start_date',
        ),
    ]
