# Generated by Django 4.2.13 on 2024-07-12 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_module_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.CharField(choices=[('36', '36ч'), ('72', '72ч')], max_length=2),
        ),
        migrations.AlterField(
            model_name='course',
            name='language',
            field=models.CharField(choices=[('ru', 'Русский'), ('en', 'Английский'), ('kg', 'Кыргызский'), ('uz', 'Узбекский'), ('kz', 'Казахский'), ('tj', 'Таджикский'), ('cn', 'Китайский')], max_length=2),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='type',
            field=models.CharField(choices=[('reading', 'Конспект'), ('video', 'Видео')], max_length=10),
        ),
        migrations.AlterField(
            model_name='module',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='usercourse',
            name='status',
            field=models.CharField(choices=[('started', 'Начато'), ('finished', 'Завершено')], max_length=10),
        ),
    ]
