# Generated by Django 4.2.13 on 2024-07-10 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_usercourse_finish_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserCourse',
        ),
    ]
