# Generated by Django 4.2.13 on 2024-07-12 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_duration_alter_course_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.CharField(choices=[('36', '36ч'), ('72', '72ч')], max_length=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='language',
            field=models.CharField(choices=[('ru', 'Русский'), ('en', 'Английский'), ('kg', 'Кыргызский'), ('uz', 'Узбекский'), ('kz', 'Казахский'), ('tj', 'Таджикский'), ('cn', 'Китайский')], max_length=15),
        ),
    ]
