# Generated by Django 4.2.13 on 2024-07-12 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_course_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.CharField(choices=[('36', '36ч'), ('72', '72ч')], max_length=10),
        ),
    ]
