# Generated by Django 4.2.13 on 2024-07-12 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_course_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration2',
            field=models.CharField(choices=[('36', '36ч'), ('72', '72ч')], default='', max_length=10),
        ),
    ]
