# Generated by Django 4.2.13 on 2024-07-12 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_course_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.CharField(blank=True, choices=[('36', '36ч'), ('72', '72ч')], default='', max_length=10, null=True),
        ),
    ]
